### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by patrick-webs** [utatti/express-formidable#13]
This library appears to use `formidable` in a non-recommended way by creating a singleton IncomingForm object and using it for all requests. We found this resulted in a memory leak that would slowly leak an unlimited amount of memory due to holding on to `IncomingMessage` objects (request objects) forever. https://github.com/utatti/express-formidable/pull/10 would likely fix the memory leak.

Compare the code of this module to the recommended code on https://github.com/felixge/node-formidable to see that they recommend creating a new `IncomingForm` per request rather than a singleton.

**Comment by utatti** [comment]
Thanks for the report. #10 has been merged.

**Comment by glyphCezilleSantillan** [comment]
Hi @utatti, the npm package doesn't seem to reflect this update yet; last publish was "2 years ago". May I request a new published version for this?
